### ISSUE TITLE
Error Starting 

### ISSUE THREAD

**Issue by Surtainss** [XeliteXirish/EliteSelfBot#7]
> eliteselfbot@1.0.0 start C:\Users\prima\Desktop\EliteSelfBot
> nodemon src/bot

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/bot.js`
C:\Users\prima\Desktop\EliteSelfBot\src\bot.js:120
    let errorMsg = error.stack.replace(new RegExp(`${__dirname}\/`, 'g'), './');
                   ^

ReferenceError: error is not defined
    at process.<anonymous> (C:\Users\prima\Desktop\EliteSelfBot\src\bot.js:120:20)
    at process.emit (events.js:315:20)
    at process._fatalException (internal/process/execution.js:169:25)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by realshaunoneill** [comment]
Bot hasn't been maintained in 3 years :( Selfbots are supported by discord anymore
